import '@client/globals.css'
import '@fortawesome/fontawesome-free/css/all.min.css'
import '@client/styles/main.scss'

export const metadata = {
    title: 'Dedicate to life-long education',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
