import { StoreShareProvider } from '@client/providers/redux.provider'
import { ComponentGetUser } from './(auth)/login/_components/getUser'

export const metadata = {
    title: 'Dedicate to life-long education',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <StoreShareProvider>
                <ComponentGetUser />
                <body>{children}</body>
            </StoreShareProvider>
        </html>
    )
}
