import Nav from "./components/nav/nav"
import "./styles/base/_reset.scss"
import "./styles/base/_layout.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="layout">
          <div className="layout-cover">
            <Nav />
            <div className="page-contain">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
